Name: Ta Xuan Minh Chau

Import the Numpy package under the name np

In [7]:
import numpy as np

Create a null vector of size 10

In [7]:
vector_2 = np.zeros(10)
vector_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a null vector of size 10 but the fifth value which is 1

In [8]:
vector_3 = np.zeros(10)
vector_3[4] = 1
vector_3

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Create a vector with values ranging from 10 to 49

In [13]:
vector_4 = np.arange(10,50)
vector_4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Reverse a vector (the first element becomes last)

In [15]:
vector_5 = np.flip(vector_4)
vector_5

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
matrix_6 = np.arange(0,9).reshape(3,3)
matrix_6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non¬zero elements from [1,2,0,0,4,0]

In [28]:
a_7 = np.array([1,2,0,0,4,0])
print ('Indices of non-zero elements')
np.where(a_7 != 0)


Indices of non-zero elements


(array([0, 1, 4], dtype=int64),)

Create a 3x3x3 array with random values

In [30]:
array_8 = np.random.rand(3,3,3)
array_8 

array([[[0.37550797, 0.97531614, 0.48285938],
        [0.36410782, 0.85039017, 0.02393929],
        [0.49391528, 0.85246497, 0.08233241]],

       [[0.95125343, 0.62473964, 0.64398647],
        [0.08933419, 0.50316504, 0.53311858],
        [0.65952065, 0.219445  , 0.08086053]],

       [[0.29472733, 0.49756315, 0.65569656],
        [0.65099274, 0.79191211, 0.8951244 ],
        [0.55074358, 0.69842434, 0.454333  ]]])

Create a random vector of size 30 and find the mean value

In [33]:
vector_9 = np.random.rand(30)
print(vector_9)
np.mean(vector_9)

[0.73151843 0.66649814 0.11594595 0.2660158  0.73713148 0.67511705
 0.83377976 0.33443755 0.5949111  0.64144836 0.36183532 0.70508066
 0.46968642 0.38094965 0.39819455 0.14371224 0.26648217 0.43933556
 0.25693151 0.95355249 0.5625784  0.10866369 0.49529348 0.8307876
 0.29582079 0.01398616 0.75511347 0.74040902 0.56057842 0.79982103]


0.5045205407298565

Create a 2d array with 1 on the border and 0 inside

In [42]:
array_10 = np.ones(36).reshape(6,6)
array_10[1:5,1:5] = 0
array_10

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

Create an 8x8 matrix and fill it with a checkerboard pattern

In [61]:
matrix_11 = np.zeros(64).reshape(8,8)
for row in range(8):
    if row%2 == 0:
        for col in range(8):
            if col%2 != 0:
                matrix_11[row,col] = 1
    else:
        for col in range(8):
            if col%2 == 0:
                matrix_11[row,col] = 1

matrix_11

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

What is the major difference between sets, lists, tuples and dictionaries?

1.Order of elements:
List items are ordered and changeable.
Tuples items are ordedred but unchangeable.
Dictionray items are unordered but changeable.
Sets items are unordered
2.How to write:
List is written by square brackets.
Tuple is written by round brackets.
Dictionary is written with curly brackets, with keys and values.
Set is written with curly brackets. 

Print first 10 natural numbers using while loop

In [22]:
i = 0
print("First 10 natural numbers")
while i < 10:
    i = i + 1
    print(i)

First 10 natural numbers
1
2
3
4
5
6
7
8
9
10


Print the numbers -10 to -1 using for loop.

In [67]:
i = -10
for n in range(10):
    print(i+n)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


Print the message “Done” after successful execution of any for a loop. 

In [37]:
i = -10
for n in range(10):
    print(i+n)
else: print("Done")

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
Done


Create a random vector of size 10 and sort it

In [6]:
vector_16 = np.random.rand(10)
vector_16_sort = np.sort(vector_16)
print(vector_16)
print(vector_16_sort)

[0.7360926  0.1117431  0.122229   0.22255798 0.39467697 0.5220561
 0.25609158 0.61575668 0.45663206 0.07520304]
[0.07520304 0.1117431  0.122229   0.22255798 0.25609158 0.39467697
 0.45663206 0.5220561  0.61575668 0.7360926 ]


Execute any three math functions using NumPy.

In [36]:
import math
v1 = np.arange(9).reshape(3,3)
v2 = np.arange(9,12)
print(v1,'\n\n', v2)
# Calculate the sum of elements following rows:
print('\nthe sum of elements following rows:',np.sum(v1, axis=1))
# Calculate the multiply of two arrays:
print('\nthe multiply of two arrays:\n', np.multiply(v1, v2))
# Calculate the multiply of two arrays:
print('\nmin of array :', np.min(v2))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [ 9 10 11]

the sum of elements following rows: [ 3 12 21]

the multiply of two arrays:
 [[ 0 10 22]
 [27 40 55]
 [54 70 88]]

min of array : 9
